package com.sunjray.osdma.PCmodel;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LetterTypeMaster generated by Smruti
 */

@Entity
@Table(name = "t_os_master_to_letter", catalog = "osdma")
public class LetterTypeMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "letter_type_id", unique = true, nullable = false)
	private Long letterTypeId;

	@Column(name = "letter_type", length = 45)
	private String letterType;

	public Long getLetterTypeId() {
		return letterTypeId;
	}

	public void setLetterTypeId(Long letterTypeId) {
		this.letterTypeId = letterTypeId;
	}

	public String getLetterType() {
		return letterType;
	}

	public void setLetterType(String letterType) {
		this.letterType = letterType;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((letterType == null) ? 0 : letterType.hashCode());
		result = prime * result + ((letterTypeId == null) ? 0 : letterTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LetterTypeMaster other = (LetterTypeMaster) obj;
		if (letterType == null) {
			if (other.letterType != null)
				return false;
		} else if (!letterType.equals(other.letterType))
			return false;
		if (letterTypeId == null) {
			if (other.letterTypeId != null)
				return false;
		} else if (!letterTypeId.equals(other.letterTypeId))
			return false;
		return true;
	}

}
