package com.sunjray.osdma.PCmodel;
// Generated Jul 29, 2019 8:46:52 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TOsMasterTeam generated by hbm2java
 */
@Entity
@Table(name = "t_os_master_team", catalog = "osdma")
public class MasterTeam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "team_id", unique = true, nullable = false)
	private Long teamId;

	@Column(name = "team_name", length = 45)
	private String teamName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterTeam", cascade = CascadeType.ALL)
	@JsonIgnoreProperties("masterTeam")
	private Set<PmTeamMember> pmTeamMembers = new HashSet<>();

	public Long getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Long teamId) {
		this.teamId = teamId;
	}

	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public Set<PmTeamMember> getPmTeamMembers() {
		return this.pmTeamMembers;
	}

	public void setPmTeamMembers(Set<PmTeamMember> pmTeamMembers) {
		this.pmTeamMembers = pmTeamMembers;
	}

	

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MasterTeam other = (MasterTeam) obj;
		if (pmTeamMembers == null) {
			if (other.pmTeamMembers != null)
				return false;
		} else if (!pmTeamMembers.equals(other.pmTeamMembers))
			return false;
		if (teamId == null) {
			if (other.teamId != null)
				return false;
		} else if (!teamId.equals(other.teamId))
			return false;
		if (teamName == null) {
			if (other.teamName != null)
				return false;
		} else if (!teamName.equals(other.teamName))
			return false;
		return true;
	}

}
