package com.sunjray.osdma.PCmodel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MasterComponent generated by hbm2java
 */
@Entity
@Table(name = "t_os_master_component", catalog = "osdma")
public class MasterComponent implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer componentId;
	private MasterProduct masterProduct;
	private String componentName;
	private String quantity;

	public MasterComponent() {
	}

	public MasterComponent(MasterProduct masterProduct, String componentName, String quantity) {
		this.masterProduct = masterProduct;
		this.componentName = componentName;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "component_id", unique = true, nullable = false)
	public Integer getComponentId() {
		return this.componentId;
	}

	public void setComponentId(Integer componentId) {
		this.componentId = componentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_id")
	public MasterProduct getMasterProduct() {
		return this.masterProduct;
	}

	public void setMasterProduct(MasterProduct masterProduct) {
		this.masterProduct = masterProduct;
	}

	@Column(name = "component_name", length = 45)
	public String getComponentName() {
		return this.componentName;
	}

	public void setComponentName(String componentName) {
		this.componentName = componentName;
	}

	@Column(name = "quantity", length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}
}
