package com.sunjray.osdma.PCmodel;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PmFundRequest generated by Smruti
 */
@Entity
@Table(name = "t_os_pm_fund_request", catalog = "osdma")
public class PmFundRequest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fund_req_id", unique = true, nullable = false)
	private Long fundReqId;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stage_of_work", referencedColumnName = "stage_id")
	private MasterWorkStage masterWorkStage;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "site_code", referencedColumnName = "sitecode_id")
	private Sitecode sitecode;

	@Column(name = "amount", precision = 10)
	private Float amount;

	@Column(name = "raised_for", nullable = false)
	private int raisedFor;

	@Column(name = "purpose", nullable = false, length = 50)
	private String purpose;

	@Column(name = "remark", length = 200)
	private String remark;

	@Column(name = "created_date", length = 19)
	private Date createdDate;

	@Column(name = "approved_amount", precision = 22, scale = 0)
	private Double approvedAmount;

	@Column(name = "approval_date", length = 19)
	private Date approvalDate;

	@Column(name = "status", length = 45)
	private String status;

	@Column(name = "bill", length = 45)
	private String bill;

	public Long getFundReqId() {
		return fundReqId;
	}

	public void setFundReqId(Long fundReqId) {
		this.fundReqId = fundReqId;
	}

	public MasterWorkStage getMasterWorkStage() {
		return masterWorkStage;
	}

	public void setMasterWorkStage(MasterWorkStage masterWorkStage) {
		this.masterWorkStage = masterWorkStage;
	}

	public Sitecode getSitecode() {
		return sitecode;
	}

	public void setSitecode(Sitecode sitecode) {
		this.sitecode = sitecode;
	}

	public Float getAmount() {
		return amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public int getRaisedFor() {
		return raisedFor;
	}

	public void setRaisedFor(int raisedFor) {
		this.raisedFor = raisedFor;
	}

	public String getPurpose() {
		return purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Double getApprovedAmount() {
		return approvedAmount;
	}

	public void setApprovedAmount(Double approvedAmount) {
		this.approvedAmount = approvedAmount;
	}

	public Date getApprovalDate() {
		return approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBill() {
		return bill;
	}

	public void setBill(String bill) {
		this.bill = bill;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((amount == null) ? 0 : amount.hashCode());
		result = prime * result + ((approvalDate == null) ? 0 : approvalDate.hashCode());
		result = prime * result + ((approvedAmount == null) ? 0 : approvedAmount.hashCode());
		result = prime * result + ((bill == null) ? 0 : bill.hashCode());
		result = prime * result + ((createdDate == null) ? 0 : createdDate.hashCode());
		result = prime * result + ((fundReqId == null) ? 0 : fundReqId.hashCode());
		result = prime * result + ((masterWorkStage == null) ? 0 : masterWorkStage.hashCode());
		result = prime * result + ((purpose == null) ? 0 : purpose.hashCode());
		result = prime * result + raisedFor;
		result = prime * result + ((remark == null) ? 0 : remark.hashCode());
		result = prime * result + ((sitecode == null) ? 0 : sitecode.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PmFundRequest other = (PmFundRequest) obj;
		if (amount == null) {
			if (other.amount != null)
				return false;
		} else if (!amount.equals(other.amount))
			return false;
		if (approvalDate == null) {
			if (other.approvalDate != null)
				return false;
		} else if (!approvalDate.equals(other.approvalDate))
			return false;
		if (approvedAmount == null) {
			if (other.approvedAmount != null)
				return false;
		} else if (!approvedAmount.equals(other.approvedAmount))
			return false;
		if (bill == null) {
			if (other.bill != null)
				return false;
		} else if (!bill.equals(other.bill))
			return false;
		if (createdDate == null) {
			if (other.createdDate != null)
				return false;
		} else if (!createdDate.equals(other.createdDate))
			return false;
		if (fundReqId == null) {
			if (other.fundReqId != null)
				return false;
		} else if (!fundReqId.equals(other.fundReqId))
			return false;
		if (masterWorkStage == null) {
			if (other.masterWorkStage != null)
				return false;
		} else if (!masterWorkStage.equals(other.masterWorkStage))
			return false;
		if (purpose == null) {
			if (other.purpose != null)
				return false;
		} else if (!purpose.equals(other.purpose))
			return false;
		if (raisedFor != other.raisedFor)
			return false;
		if (remark == null) {
			if (other.remark != null)
				return false;
		} else if (!remark.equals(other.remark))
			return false;
		if (sitecode == null) {
			if (other.sitecode != null)
				return false;
		} else if (!sitecode.equals(other.sitecode))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		return true;
	}

}
