package com.sunjray.osdma.PCmodel;
// Generated Jul 29, 2019 8:46:52 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOsPcSurveySite generated by hbm2java
 */
@Entity
@Table(name = "t_os_pc_survey_site", catalog = "osdma")
public class SiteSurvey implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer surveyId;
	private Sitecode siteCode;
	private Date surveyDate;
	private String remark;
	private String surveyDoc;
	private Integer createdBy;
	private Date createdOn;
	private Integer updatedBy;
	private Date updatedOn;

	public SiteSurvey() {
	}

	public SiteSurvey(Sitecode siteCode, Date surveyDate, String remark, String surveyDoc, Integer createdBy,
			Date createdOn, Integer updatedBy, Date updatedOn) {
		this.siteCode = siteCode;
		this.surveyDate = surveyDate;
		this.remark = remark;
		this.surveyDoc = surveyDoc;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "survey_id", unique = true, nullable = false)
	public Integer getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	@ManyToOne
	@JoinColumn(name = "site_code", referencedColumnName = "sitecode_id")
	public Sitecode getSiteCode() {
		return siteCode;
	}

	public void setSiteCode(Sitecode siteCode) {
		this.siteCode = siteCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "survey_date", length = 19)
	public Date getSurveyDate() {
		return this.surveyDate;
	}

	public void setSurveyDate(Date surveyDate) {
		this.surveyDate = surveyDate;
	}

	@Column(name = "remark", length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "survey_doc", length = 45)
	public String getSurveyDoc() {
		return this.surveyDoc;
	}

	public void setSurveyDoc(String surveyDoc) {
		this.surveyDoc = surveyDoc;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
