package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TOsAmConsingementTrackC2p generated by hbm2java
 */
@Entity
@Table(name = "t_os_am_consingement_track_c2p", catalog = "osdma")
public class AmConsingementTrackC2p implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer consignmentId;
	private Integer consingementNo;
	private String airwaybillNo;
	private String status;
	private Date expArrivalDate;
	private Date actArrivalDate;
	private Date updatedOn;
	private Integer createdBy;
	private Date createdOn;
	private Integer modifyBy;
	private Date modifyOn;
	private Set<AmConsignmentMateriallist> amConsignmentMateriallists = new HashSet<>();

	public AmConsingementTrackC2p() {
	}

	public AmConsingementTrackC2p(Integer consingementNo, String airwaybillNo, String status, Date expArrivalDate,
			Date actArrivalDate, Date updatedOn, Integer createdBy, Date createdOn, Integer modifyBy, Date modifyOn,
			Set<AmConsignmentMateriallist> amConsignmentMateriallists) {
		this.consingementNo = consingementNo;
		this.airwaybillNo = airwaybillNo;
		this.status = status;
		this.expArrivalDate = expArrivalDate;
		this.actArrivalDate = actArrivalDate;
		this.updatedOn = updatedOn;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "consignment_id", unique = true, nullable = false)
	public Integer getConsignmentId() {
		return this.consignmentId;
	}

	public void setConsignmentId(Integer consignmentId) {
		this.consignmentId = consignmentId;
	}

	@Column(name = "consingement_no")
	public Integer getConsingementNo() {
		return this.consingementNo;
	}

	public void setConsingementNo(Integer consingementNo) {
		this.consingementNo = consingementNo;
	}

	@Column(name = "airwaybill_no", length = 45)
	public String getAirwaybillNo() {
		return this.airwaybillNo;
	}

	public void setAirwaybillNo(String airwaybillNo) {
		this.airwaybillNo = airwaybillNo;
	}

	@Column(name = "status", length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exp_arrival_date", length = 19)
	public Date getExpArrivalDate() {
		return this.expArrivalDate;
	}

	public void setExpArrivalDate(Date expArrivalDate) {
		this.expArrivalDate = expArrivalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "act_arrival_date", length = 19)
	public Date getActArrivalDate() {
		return this.actArrivalDate;
	}

	public void setActArrivalDate(Date actArrivalDate) {
		this.actArrivalDate = actArrivalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_on", length = 19)
	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amConsingementTrackC2p")
	public Set<AmConsignmentMateriallist> getAmConsignmentMateriallists() {
		return amConsignmentMateriallists;
	}

	public void setAmConsignmentMateriallists(Set<AmConsignmentMateriallist> amConsignmentMateriallists) {
		this.amConsignmentMateriallists = amConsignmentMateriallists;
	}

}
