package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AmConsignmentMateriallist generated by hbm2java
 */
@Entity
@Table(name = "t_os_am_consignment_materiallist", catalog = "osdma")
public class AmConsignmentMateriallist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer materialId;
	private AmConsingementTrackC2p amConsingementTrackC2p;
	private String itemName;
	private String serialNo;
	private Integer quantity;
	private Integer createdBy;
	private Date createdOn;
	private Integer modifyBy;
	private Date modifyOn;

	public AmConsignmentMateriallist() {
	}

	public AmConsignmentMateriallist(AmConsingementTrackC2p amConsingementTrackC2p, String itemName, String serialNo,
			Integer quantity, Integer createdBy, Date createdOn, Integer modifyBy, Date modifyOn) {
		this.amConsingementTrackC2p = amConsingementTrackC2p;
		this.itemName = itemName;
		this.serialNo = serialNo;
		this.quantity = quantity;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "material_id", unique = true, nullable = false)
	public Integer getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "consinment_id")
	public AmConsingementTrackC2p getAmConsingementTrackC2p() {
		return this.amConsingementTrackC2p;
	}

	public void setAmConsingementTrackC2p(AmConsingementTrackC2p amConsingementTrackC2p) {
		this.amConsingementTrackC2p = amConsingementTrackC2p;
	}

	@Column(name = "item_name", length = 45)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "serial_no", length = 45)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_on", length = 19)
	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

}
