package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsignmentTrackP2a generated by hbm2java
 */
@Entity
@Table(name = "t_os_consignment_track_p2a", catalog = "osdma")
public class ConsignmentTrackP2a implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -100510376370343266L;
	private Integer trackP2aId;
	private AmConsignmentLogistic AmConsignmentLogistic;
	private Date expectedArrival;
	private Date actualArrival;
	private Date pickupDate;
	private Integer createdBy;
	private Date createdOn;
	private Integer updatedBy;
	private Date updatedOn;

	public ConsignmentTrackP2a() {
	}

	public ConsignmentTrackP2a(AmConsignmentLogistic AmConsignmentLogistic, Date expectedArrival, Date actualArrival,
			Date pickupDate, Integer createdBy, Date createdOn, Integer updatedBy, Date updatedOn) {
		this.AmConsignmentLogistic = AmConsignmentLogistic;
		this.expectedArrival = expectedArrival;
		this.actualArrival = actualArrival;
		this.pickupDate = pickupDate;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "track_p2a_id", unique = true, nullable = false)
	public Integer getTrackP2aId() {
		return this.trackP2aId;
	}

	public void setTrackP2aId(Integer trackP2aId) {
		this.trackP2aId = trackP2aId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "log_consignment_id")
	public AmConsignmentLogistic getAmConsignmentLogistic() {
		return this.AmConsignmentLogistic;
	}

	public void setAmConsignmentLogistic(AmConsignmentLogistic AmConsignmentLogistic) {
		this.AmConsignmentLogistic = AmConsignmentLogistic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expected_arrival", length = 19)
	public Date getExpectedArrival() {
		return this.expectedArrival;
	}

	public void setExpectedArrival(Date expectedArrival) {
		this.expectedArrival = expectedArrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_arrival", length = 19)
	public Date getActualArrival() {
		return this.actualArrival;
	}

	public void setActualArrival(Date actualArrival) {
		this.actualArrival = actualArrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pickup_date", length = 19)
	public Date getPickupDate() {
		return this.pickupDate;
	}

	public void setPickupDate(Date pickupDate) {
		this.pickupDate = pickupDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_on", length = 10)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
