package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOsMasterServprovrType generated by hbm2java
 */
@Entity
@Table(name = "t_os_master_servprovr_type", catalog = "osdma")
public class MasterServprovrType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer serviceProviderId;
	private String serviceProviderType;
	private String serviceProviderDescription;
	private Integer createdBy;
	private Integer updatedBy;
	private Date createdOn;
	private Date updatedOn;

	public MasterServprovrType() {
	}

	public MasterServprovrType(String serviceProviderType, String serviceProviderDescription, Integer createdBy,
			Integer updatedBy, Date createdOn, Date updatedOn) {
		this.serviceProviderType = serviceProviderType;
		this.serviceProviderDescription = serviceProviderDescription;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_provider_id", unique = true, nullable = false)
	public Integer getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(Integer serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	@Column(name = "service_provider_type", length = 45)
	public String getServiceProviderType() {
		return this.serviceProviderType;
	}

	public void setServiceProviderType(String serviceProviderType) {
		this.serviceProviderType = serviceProviderType;
	}

	@Column(name = "service_provider_description", length = 45)
	public String getServiceProviderDescription() {
		return this.serviceProviderDescription;
	}

	public void setServiceProviderDescription(String serviceProviderDescription) {
		this.serviceProviderDescription = serviceProviderDescription;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}
}
