package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOsSerProPersonalDtls generated by hbm2java
 */
@Entity
@Table(name = "t_os_ser_pro_personal_dtls", catalog = "osdma")
public class SerProPersonalDtls implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer providerId;
	private MasterServprovrType TOsMasterServprovrType;
	private String providerName;
	private Integer contactNo;
	private String emailId;
	private Integer createdBy;
	private Date createdOn;
	private Integer modifyBy;
	private Date modifyOn;

	public SerProPersonalDtls() {
	}

	public SerProPersonalDtls(MasterServprovrType TOsMasterServprovrType, String providerName, Integer contactNo,
			String emailId, Integer createdBy, Date createdOn, Integer modifyBy, Date modifyOn) {
		this.TOsMasterServprovrType = TOsMasterServprovrType;
		this.providerName = providerName;
		this.contactNo = contactNo;
		this.emailId = emailId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "provider_id", unique = true, nullable = false)
	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service_type_id")
	public MasterServprovrType getTOsMasterServprovrType() {
		return this.TOsMasterServprovrType;
	}

	public void setTOsMasterServprovrType(MasterServprovrType TOsMasterServprovrType) {
		this.TOsMasterServprovrType = TOsMasterServprovrType;
	}

	@Column(name = "provider_name", length = 45)
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "contact_no")
	public Integer getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(Integer contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "email_id", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_on", length = 19)
	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

}
