package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sunjray.osdma.PCenumeration.Status;
import com.sunjray.osdma.PCmodel.Sitecode;

/**
 * ServProBill generated by hbm2java
 */
@Entity
@Table(name = "t_os_serv_pro_bill", catalog = "osdma")
public class ServProBill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer billId;
	private SerProPersonalDtls serProPersonalDtls;
	private String billNo;
	private Double billAmount;
	private Double paidAmount;
	private Date billDate;
	private Date paymentDate;
	private Integer createdBy;
	private Date createdOn;
	private Integer modifyBy;
	private Date modifyOn;
	private Sitecode sitecode;
	private AmConsingementTrackC2p amConsingementTrackC2p;
	private Status status;
	private Set<ServProvBillDoc> servProvBillDocs = new HashSet<>();

	public ServProBill() {
	}

	public ServProBill(Status status) {
		this.status = status;
	}

	public ServProBill(SerProPersonalDtls serProPersonalDtls, String billNo, Double billAmount, Double paidAmount,
			Date billDate, Date paymentDate, Integer createdBy, Date createdOn, Integer modifyBy, Date modifyOn,
			Sitecode sitecode, AmConsingementTrackC2p amConsingementTrackC2p, Status status,
			Set<ServProvBillDoc> servProvBillDocs) {
		this.serProPersonalDtls = serProPersonalDtls;
		this.billNo = billNo;
		this.billAmount = billAmount;
		this.paidAmount = paidAmount;
		this.billDate = billDate;
		this.paymentDate = paymentDate;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.sitecode = sitecode;
		this.amConsingementTrackC2p = amConsingementTrackC2p;
		this.status = status;
		this.servProvBillDocs = servProvBillDocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bill_id", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provider_id")
	public SerProPersonalDtls getSerProPersonalDtls() {
		return this.serProPersonalDtls;
	}

	public void setSerProPersonalDtls(SerProPersonalDtls serProPersonalDtls) {
		this.serProPersonalDtls = serProPersonalDtls;
	}

	@Column(name = "bill_no", length = 45)
	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	@Column(name = "bill_amount", precision = 22, scale = 0)
	public Double getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(Double billAmount) {
		this.billAmount = billAmount;
	}

	@Column(name = "paid_amount", precision = 22, scale = 0)
	public Double getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(Double paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bill_date", length = 19)
	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_on", length = 19)
	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sitecode_id")
	public Sitecode getSitecodeId() {
		return this.sitecode;
	}

	public void setSitecodeId(Sitecode sitecode) {
		this.sitecode = sitecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consignment_id")
	public AmConsingementTrackC2p getAmConsingementTrackC2p() {
		return amConsingementTrackC2p;
	}

	public void setAmConsingementTrackC2p(AmConsingementTrackC2p amConsingementTrackC2p) {
		this.amConsingementTrackC2p = amConsingementTrackC2p;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status", nullable = false, length = 8)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servProBill")
	public Set<ServProvBillDoc> getServProvBillDocs() {
		return this.servProvBillDocs;
	}

	public void setServProvBillDocs(Set<ServProvBillDoc> servProvBillDocs) {
		this.servProvBillDocs = servProvBillDocs;
	}

}
