package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOsWarhouseaStockOut generated by hbm2java
 */
@Entity
@Table(name = "t_os_warhousea_stock_out", catalog = "osdma")
public class WarhouseaStockOut implements java.io.Serializable {

	private Integer warhouseaStockOutId;
	private String consigner;
	private String consignee;
	private String storageLocation;
	private Integer quantity;
	private QaqcItems qaqcItems;
	private Date createdDate;

	public WarhouseaStockOut() {
	}

	public WarhouseaStockOut(String consigner, String consignee, String storageLocation, Integer quantity,
			QaqcItems qaqcItems, Date createdDate) {
		this.consigner = consigner;
		this.consignee = consignee;
		this.storageLocation = storageLocation;
		this.quantity = quantity;
		this.qaqcItems = qaqcItems;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "warhousea_stock_out_id", unique = true, nullable = false)
	public Integer getWarhouseaStockOutId() {
		return this.warhouseaStockOutId;
	}

	public void setWarhouseaStockOutId(Integer warhouseaStockOutId) {
		this.warhouseaStockOutId = warhouseaStockOutId;
	}

	@Column(name = "consigner", length = 50)
	public String getConsigner() {
		return this.consigner;
	}

	public void setConsigner(String consigner) {
		this.consigner = consigner;
	}

	@Column(name = "consignee", length = 50)
	public String getConsignee() {
		return this.consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	@Column(name = "storage_location", length = 50)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_id")
	public QaqcItems getQaqcItems() {
		return this.qaqcItems;
	}

	public void setQaqcItems(QaqcItems qaqcItems) {
		this.qaqcItems = qaqcItems;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
