package com.sunjray.osdma.SMwarehouseAModel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WarhouseaMaterialLst generated by hbm2java
 */
@Entity
@Table(name = "t_os_warhousea_material_lst", catalog = "osdma")
public class WarhouseaMaterialLst implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer materialListId;
	private AmConsignmentMateriallist amConsignmentMateriallist;
	private String storageLocation;
	private String rackList;
	private Date createdDate;
	private Integer createdBy;

	public WarhouseaMaterialLst() {
	}

	public WarhouseaMaterialLst(AmConsignmentMateriallist amConsignmentMateriallist, String storageLocation,
			String rackList, Date createdDate, Integer createdBy) {
		this.amConsignmentMateriallist = amConsignmentMateriallist;
		this.storageLocation = storageLocation;
		this.rackList = rackList;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "material_list_id", unique = true, nullable = false)
	public Integer getMaterialListId() {
		return this.materialListId;
	}

	public void setMaterialListId(Integer materialListId) {
		this.materialListId = materialListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "material_id")
	public AmConsignmentMateriallist getAmConsignmentMateriallist() {
		return this.amConsignmentMateriallist;
	}

	public void setAmConsignmentMateriallist(AmConsignmentMateriallist amConsignmentMateriallist) {
		this.amConsignmentMateriallist = amConsignmentMateriallist;
	}

	@Column(name = "storage_location", length = 50)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "rack_list", length = 20)
	public String getRackList() {
		return this.rackList;
	}

	public void setRackList(String rackList) {
		this.rackList = rackList;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

}
